### ISSUE TITLE
Update TAC charter with membership details

### ISSUE THREAD

**Issue by sarob** [ucfoundation/tac#17]
As discussed in the 11 sep 19 TAC meeting, a simple process to propose new members is needed. A simple request to become a TAC member to the mailing list while requiring an existing TAC member sponsor and 2/3 TAC approval.  I understand that a PR will be created proposing the process above to be added to the TAC charter. 

I add to the discussion:

1. Should there be lower or upper boundary limits to the number of TAC members?
1. Should there be limit to the number representatives from any one project or company?
1. As new projects get added to UCF, a process of automatically including their representative to the TAC could encourage participation.

**Comment by danlopez00** [comment]
@sarob To clarify for the conversation, the topic is focused on the voting and membership details re: representation, nomination process, and membership count limits per org. Please confirm.

**Comment by sarob** [comment]
Issue name could have been TAC membership outline. I thought through what would be the next questions and then posted them here. No reason to get too crazy on the what if scenarios.
