### ISSUE TITLE
Elect TAC Chair

### ISSUE THREAD

**Issue by caniszczyk** [ucfoundation/tac#2]
The TAC is responsible for electing a chair, who will preside over meetings of the TAC.

We would propose the following election procedure for consideration:

* We call for nominations via email (to be sent out today) to all of the TAC members, with Friday, 8 pm PT, May 31, being the close of the nomination period.
* We will distribute a slate of nominees together with bios and/or statements of intent, and open an email voting period which will close Wednesday, 8 pm PT, June 5.
* We generally have nominations made via ‘reply all’ to our call for nominations email, and then ask for direct emails to us for the actual voting.

**Comment by danlopez00** [comment]
Per TAC communication:

The TAC is responsible for electing a chair, who will preside over meetings of the TAC.

We would propose the following election procedure for consideration:

- We call for nominations via email (to be sent out today) to all of the TAC members, with Friday, 8 pm PT, May 31, being the close of the nomination period.  [COMPLETE]
- The result was this TAC thread: https://lists.uc.foundation/g/ucf-tac/topic/tac_chair_elections/31870469?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,31870469
- @tgorkin has volunteered to be the chair for the first term and is the defacto nominee from the TAC
